package com.example.hilossegundotrimestre.Bestiario

import android.content.Intent
import android.media.MediaPlayer
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.view.View
import android.widget.GridView
import android.widget.TextView
import com.example.hilossegundotrimestre.R

class ListaActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_lista)

        val monstruo = item_Monstruo("Altaroth","Neopteron", "Pequeño", "Sin elemento", 1, "Insectos abundantes en muchas zonas. Absorben fruta, setas y miel, y después las llevan al nido. En esos momentos es posible conseguir materiales de sis hinchados abdómenes, cuyo color cambia según la carga.", R.mipmap.altaroth, R.raw.resto, R.raw.notfoundintro)
        val monstruo2 = item_Monstruo("Apceros", "Herbívoro", "Pequeño", "Sin elemento", 1, "Herbívoros desérticos de grueso blindaje. De carácter territorial, son conocidos por perseguir sin descanso a cualquier intruso que se entrometa en su hábitat. Muy hostiles con los cazadores, que suelen robar huevos de sus nidos.", R.mipmap.apceros, R.raw.resto, R.raw.notfoundintro)
        val monstruo3 = item_Monstruo("Aptonoth", "Herbívoro", "Pequeño", "Sin elemento", 1, "Herbívoros relativamente dóciles con crestas características. Forman grupos, crían comunalmente a los jóvenes y se han usado como animales de carga durante generaciones. Su carne es sabrosa. Muy cautos con monstruos grandes.", R.mipmap.aptonoth, R.raw.resto, R.raw.notfoundintro)
        val monstruo4 = item_Monstruo("Bnahabra", "Neopteron", "Pequeño", "Sin elemento", 1, "Insectos aéreos abundantes que atacan con veneno paralizante y ponen huevos en la carroña junto a un fluido que acelera la descomposición. Es preferible matarlos con veneno para que su cuerpo se mantenga disponible para el corte.", R.mipmap.bnahabra, R.raw.resto, R.raw.notfoundintro)
        val monstruo5 = item_Monstruo("Cephalos", "Wyvern Nadador", "Pequeño", "Sin elemento", 2, "El color de estos wyverns nadadores casa con los desiertos en los que viven. Excavadores expertos, nadan por la arena en manadas y apenas suelen salir a la superficie. Su oído está muy desarrollado y un impacto en el suelo hará que salgan.", R.mipmap.cephalos, R.raw.resto, R.raw.notfoundintro)
        val monstruo6 = item_Monstruo("Conga", "Bestia Colmillo", "Pequeño", "Sin elemento", 2, "Bestia de colmillos de aspecto simiesco y pelaje rosado. Los Conga prefieren vivir en grupos pequeños, y suelen habitar en lugares templados y húmedos.", R.mipmap.conga, R.raw.resto, R.raw.notfoundintro)
        val monstruo7 = item_Monstruo("Delex", "Wyvern Nadador", "Pequeño", "Sin elemento", 2, "Monstruos carnívoros desérticos que viajan en bancos de cuatro o cinco. Los Delex suelen seguir a grandes depredadores con la esperanza de rapiñar carroña y se ven a menudo a bordo de surcadunas de cacería. Son muy sensibles al ruido.", R.mipmap.delex, R.raw.resto, R.raw.notfoundintro)
        val monstruo8 = item_Monstruo("Felyne", "Lynian", "Pequeño", "Sin elemento", 1, "Criaturas bípedas parecidas a los gatos, conocidas por su pelo claro. Son dóciles, pero atacan fieramente si se les provoca. Muy curiosos. Algunos intentan entrar en la sociedad humana. Les encanta el aroma de la Vid Felyne.", R.mipmap.felyne, R.raw.resto, R.raw.notfoundintro)
        val monstruo9 = item_Monstruo("Gargwa", "Herbívoro", "Pequeño", "Sin elemento", 1, "Wyverns pájaro no voladores habitantes de las llanuras con vestigios de alas. Muy tímidos, se sabe que los Gargwa a veces ponen huevos en el momento que son sorprendidos por la espalda por otra criatura. Se crían en muchas aldeas.", R.mipmap.gargwa, R.raw.resto, R.raw.notfoundintro)
        val monstruo10 = item_Monstruo("Genprey", "Wyvern Pájaro", "Pequeño", "Sin elemento", 1, "Wyverns pájaro de llamativa piel verde y naranja a rayas. Los Genprey viven en grupos en Sima Hueca y en la Selva Jurásica. Sus garras y grandes colmillos contienen neurotoxinas paralizantes que usan para aturdir a sus presas.", R.mipmap.genprey, R.raw.resto, R.raw.notfoundintro)
        val monstruo11 = item_Monstruo("Hermitaur", "Carapaceon", "Pequeño", "Sin elemento", 2, "Este pequeño carapaceon de duro caparazón abunda en el desierto, donde acecha bajo las arenas y emerge al acercarse una presa. Sus cerebros se consideran una auténtica delicia.", R.mipmap.hermitaur, R.raw.resto, R.raw.notfoundintro)
        val monstruo12 = item_Monstruo("Loprey", "Wyvern Pájaro", "Pequeño", "Sin elemento", 3, "Especie de pequeño carnívoro de color rojo vivo que habita las zonas subtropicales. Las bolsas de su garganta acumulan un poderoso veneno que agota lentamente la salud de la presa.", R.mipmap.loprey, R.raw.resto, R.raw.notfoundintro)
        val monstruo13 = item_Monstruo("Jaggi", "Wyvern Pájaro", "Pequeño", "Sin elemento", 2, "Wyverns pájaro carnívoros y muy sociables que viven en grandes grupos. Los Jaggi jóvenes cazan en grupo cuando atacan animales grandes y roban huevos. Se cree que actúan a las ordenes de un único macho dominante.", R.mipmap.jaggi, R.raw.resto, R.raw.notfoundintro)
        val monstruo14 = item_Monstruo("Jaggia", "Wyvern Pájaro", "Pequeño", "Sin elemento", 2, "Jaggi hembra que se mueven en manadas. Las Jaggia viven cerca del nido y se encargan de defender y cuidar a las crías. Más pequeñas que los machos adultos, pero mayores y más fuertes que los machos jóvenes. Obedecen al macho dominante.", R.mipmap.jaggia, R.raw.resto, R.raw.notfoundintro)
        val monstruo15 = item_Monstruo("Kelbi", "Herbívoro", "Pequeño", "Sin elemento", 1, "Pequeños herbívoros famosos por su gentileza, además de por las propiedades medicinales de sus cuernos. Es necesario aturdir al Kelbi con golpes contundentes para cortar su cuerno sin matarlo.", R.mipmap.kelbi, R.raw.resto, R.raw.notfoundintro)
        val monstruo16 = item_Monstruo("Konchu", "Neopteron", "Pequeño", "Sin elemento", 1, "Neopterones que viajan largas distancias para alimentarse, y que pueden sobrevivir en casi cualquier entorno. Los Konchu forman una pelota y ruedan para protegerse y para espantar a su enemigo. Sus robustas corazas son fáciles de obtener, y son muy valoradas por los herreros.", R.mipmap.konchu, R.raw.resto, R.raw.notfoundintro)
        val monstruo17 = item_Monstruo("Melynx", "Lynian", "Pequeño", "Sin elemento", 2, "Criaturas bípedas semejantes a un gato, conocidas por su pelo oscuro. Más curiosos que los Felyne y ávidos cleptómanos, los Melynx llevan su botín a sus madrigueras. La vid Felyne los intoxica y hace que suelten objetos.", R.mipmap.melynx, R.raw.resto, R.raw.notfoundintro)
        val monstruo18 = item_Monstruo("Popo", "Herbívoro", "Pequeño", "Sin elemento", 1, "Herbívoros que forman grupos. De pelaje abundante para soportar el frío. Son dóciles, pero usan con valor sus grandes colmillos al defender a sus crías. Su carne es muy nutritiva; la lengua de Popo se considera un manjar.", R.mipmap.popo, R.raw.resto, R.raw.notfoundintro)
        val monstruo19 = item_Monstruo("Remobra", "Wyvern Serpiente", "Pequeño", "Sin elemento", 3, "Wyvern voladores pequeños y ágiles que buscan criaturas debilitadas a las que atacar. Se suelen ver cerca de dragones ancianos y se consideran de mal agüero. Tras descubrir al Najarala, se les reclasificó como wyverns serpiente.", R.mipmap.remobra, R.raw.resto, R.raw.notfoundintro)
        val monstruo20 = item_Monstruo("Rhenoplos", "Herbívoro", "Pequeño", "Sin elemento", 1, "Herbívoros territoriales de muy escasa visión, pero de oído preciso. Un Rhenoplos perseguirá a cualquier objetivo que oiga. A menudo chocan con piedras, tal vez porque no pueden parar fácilmente una vez se han echado a correr.", R.mipmap.rhenoplos, R.raw.resto, R.raw.notfoundintro)
        val monstruo21 = item_Monstruo("Slagtoth", "Herbívoro", "Pequeño", "Sin elemento", 1, "Herbívoros que habitan en zonas costeras. Su pesada piel caída contiene nutrientes, y es muy apreciada por su resistencia al calor y al agua. Los machos son muy territoriales, y a veces no huyen de los wyverns.", R.mipmap.slagtoth, R.raw.resto, R.raw.notfoundintro)
        val monstruo22 = item_Monstruo("Velociprey", "Wyvern Pájaro", "Pequeño", "Sin elemento", 2, "Monstruos carnívoros agresivos que viajan y cazan en grupo. Hasta los maestros cazadores procuran no verse rodeados por estos depredadores. En esta región se sabe que habitan en el Vergel Eterno.", R.mipmap.velociprey, R.raw.resto, R.raw.notfoundintro)
        val monstruo23 = item_Monstruo("Zamite", "Anfibio", "Pequeño", "Sin elemento", 2, "Zamtrios jóvenes que usan sus afilados dientes para perforar la piel de su presa y meterse dentro para consumirlos desde el interior; si te atacan, rueda repetidamente para liberarte. Los Zamite crecen rápido, incluso después de cada comida.", R.mipmap.zamite, R.raw.resto, R.raw.notfoundintro)
        val monstruo24 = item_Monstruo("Akantor", "Wyvern Volador", "Grande", "Fuego", 7, "Un Wyvern rodeado de misterio y conocido por muchos nombres: \"Dios Oscuro\" para algunos, \"Tirano de Fuego\" para otros, pero el gremio suele llamarlo \"Akantor\". Sus colmillos y espinas gigantes son una visión terrible en zonas volcánicas.", R.mipmap.akantor, R.raw.akantor, R.raw.akantorintro)
        val monstruo25 = item_Monstruo("Basarios", "Wyvern Volador", "Grande", "Fuego", 4, "Gravios jóvenes famosos por sus caparazones duros como piedras. Suelen enterrarse bajo tierra, imitando a las rocas y atacando a mineros despistados. También se los conoce por emitir gases venenosos, y por su debilidad contra bombas.", R.mipmap.basarios, R.raw.basarios, R.raw.basariosintro)
        val monstruo26 = item_Monstruo("Basarios Bermejo", "Wyvern Volador", "Grande", "Fuego", 4, "Una variante de Basarios que cubre su espalda de cristales para defenderse, ofreciendo una oportunidad de extraer minerales raros. Salta sobre uno cuando su caparazón trasero esté roto para que gire y exponga su débil barriga.", R.mipmap.basariosbermejo, R.raw.basarios, R.raw.notfoundintro)
        val monstruo27 = item_Monstruo("Brachydios", "Wyvern Brutal", "Grande", "Sin elemento", 3, "Wyvern brutos recubiertos de una sustancia verde explosiva, ya que contiene un moho viscoso, que entra en combustión con una enzima presente en la saliva del monstruo. También pueden asestar poderosos golpes con sus patas delanteras.", R.mipmap.brachydios, R.raw.brachidios, R.raw.brachidiosintro)
        val monstruo28 = item_Monstruo("Brachydios Colérico", "Wyvern Brutal", "Grande", "Sin elemento", 10, "\tVariedad de Brachydios más grande de lo habitual en la especie. La baba que recubre su cuerpo se activa y explota con el tiempo.", R.mipmap.brachydiosrabioso, R.raw.brachidios, R.raw.notfoundintro)
        val monstruo29 = item_Monstruo("Cephadrome", "Wyvern Nadador", "Grande", "Agua", 3, "Los líderes de los rebaños de Cephalos. Estas criaturas son más grandes y cuentan con escamas duras y negras. Al igual que los más pequeños, tienen un oído excelente, por lo que son débiles a ruidos fuertes. Pueden paralizar.\n", R.mipmap.cephadrome, R.raw.cephadrome, R.raw.cephadromeintro)
        val monstruo30 = item_Monstruo("Congalala", "Bestia Colmillos", "Grande", "Fuego", 2, "Gran bestia de largos colmillos y pelaje rosado que se encuentra en regiones templadas y húmedas. Comedores habituales de setas, los Congalala cuentan con veneno o aliento flamígero, según los tipos que abunden en su hábitat.\n", R.mipmap.congalala, R.raw.congalala, R.raw.congalalaintro)
        val monstruo31 = item_Monstruo("Congalala Esmeralda", "Bestia Colmillos", "Grande", "Fuego", 4, "Variante de Congalala de pelaje verde y cresta muy prominente. Más voraz que otros Congalala, puede almacenar más gas en su cuerpo, lo que le permite emitir flatulencias de mayor alcance si lo amenazan o provocan.\n", R.mipmap.congalalaesmeralda, R.raw.congalala, R.raw.notfoundintro)
        val monstruo32 = item_Monstruo("Daimyo Hermitaur", "Carapaceon", "Grande", "Agua", 8, "Un Carapaceon que ataca con sus pinzas y aliento burbujeante. Si el enorme cráneo que lleva encima resulta destruido, huirá en busca de otro cascarón para convertirlo en su hogar.\n", R.mipmap.daimyohermitaur, R.raw.daimyohermitaur, R.raw.dahrenmohranintro)
        val monstruo33 = item_Monstruo("Daimyo Hermitaur Morado", "Carapaceon", "Grande", "Agua", 8, "Un carapaceon grande de un color llamativo y un enorme cráneo de monstruo a la espalda. Al contrario que otras variedades más comunes, esta salta hacia sus enemigos, motivo por el que es especialmente peligroso.\n", R.mipmap.daimyohermitaurmorado, R.raw.daimyohermitaur, R.raw.notfoundintro)
        val monstruo34 = item_Monstruo("Diablos", "Wyvern Volador", "Grande", "Sin elemento", 9, "Un wyvern del desierto que recibe su nombre de los cuernos de su cabeza. Al igual que los Monoblos, el Diablos carga contra su presa o ataca desde el suelo y es más veloz al enfadarse. Su agudo oído lo hace sensible a bombas sónicas.\n", R.mipmap.diablos, R.raw.diablos, R.raw.diablosintro)
        val monstruo35 = item_Monstruo("Diablos Negro", "Wyvern Volador", "Grande", "Sin elemento", 9, "Se considera a estos Diablos oscuros una subespecie, pero son Diablos hembra en celo. El cambio de color es un aviso para el resto de criaturas, pues suelen volverse muy agresivas en época de apareamiento.\n", R.mipmap.diablosnegro, R.raw.diablos, R.raw.notfoundintro)
        val monstruo36 = item_Monstruo("Deviljho", "Wyvern Brutal", "Grande", "Draco", 7, "Los temidos Deviljho nómadas no tienen un territorio propio. Sus músculos se hinchan si se les provoca, revelando viejas heridas. Necesitan alimentarse sin cesar debido a su elevada temperatura corporal, y pueden cazar hasta extinguir especies.\n", R.mipmap.deviljho, R.raw.deviljho, R.raw.notfoundintro)
        val monstruo37 = item_Monstruo("Deviljho Despiadado", "Wyvern Volador", "Grande", "Draco", 6, "El terrible y nómada Deviljho no tiene territorio. Si se le provoca, se le hinchan los músculos y revelan viejas heridas. Necesita alimento continuo por su alto calor corporal. Pueden extinguir a animales cercanos.", R.mipmap.deviljhodespiadado, R.raw.deviljho, R.raw.notfoundintro)
        val monstruo38 = item_Monstruo("Gendrome", "Wyvern Pájaro", "Grande", "Sin elemento", 2, "Monstruos dominantes que dirigen las manadas de Genprey. Más grandes que sus hermanos y de cresta más prominente, los Gendrome usan el veneno de sus colmillos y garras hiperdesarrollados para paralizar a sus presas.\n", R.mipmap.gendrome, R.raw.velocidromeygendrome, R.raw.gendromeintro)
        val monstruo39 = item_Monstruo("Gore Magala", "???", "Grande", "Sin elemento", 3, "Un monstruo curioso que cuando se ve amenazado expele escamas en forma de polen, que mejoran sus sentidos y tienen efectos nocivos para las demás criaturas que las inhalan. Tan huidizos como misteriosos.\n", R.mipmap.goremagala, R.raw.goremagala, R.raw.goremagalaintro)
        val monstruo40 = item_Monstruo("Gore Magala Caótico", "???", "Grande", "Sin elemento", 10, "Este ejemplar sólo es encontrado en zonas cercanas al territorio del Shagaru Magala, sobre todo el Monte Cielo, ya que la razón de que no haya logrado mudar es porque la niebla del Shagaru impide que se complete este proceso.", R.mipmap.goremagalacaotico, R.raw.goremagala, R.raw.notfoundintro)
        val monstruo41 = item_Monstruo("Shagaru Magala", "Dragón Anciano", "Grande", "Sin elemento", 7, "El brillo particular que irradia este Gore Magala se ha avistado en la Zona Sagrada del Monte Cielo. Se cree que el Shagaru Magala era el \"viento corrupto que marchitó una montaña\", una calamidad que narran las antiguas escrituras.\n", R.mipmap.shagarumagala, R.raw.shagarumagala, R.raw.shagarumagalaintro)
        val monstruo42 = item_Monstruo("Gravios", "Wyvern Volador", "Grande", "Fuego", 3, "Wyverns grandes que se hallan en zonas volcánicas. Tienen un feroz ataque de aliento ardiente y pueden emitir un gas adormecedor. Sus caparazones óseos son muy duros, pero dejan expuesto un interior frágil.", R.mipmap.gravios, R.raw.gravios, R.raw.notfoundintro)
        val monstruo43 = item_Monstruo("Gravios Negro", "Wyvern Volador", "Grande", "Fuego", 6, "Una subespecie de Gravios que destaca por un caparazón negro duro que le permite mantener su elevada temperatura interna. A veces, descarga esta energía térmica en forma de poderoso rayo calorífico", R.mipmap.graviosnegro, R.raw.gravios, R.raw.notfoundintro)
        val monstruo44 = item_Monstruo("Gran Jaggi", "Wyvern Pájaro", "Grande", "Sin elemento", 1, "El Gran Jaggi es el lider de la manada Jaggi. A cierta edad, los machos dejan la manada para vivir por su cuenta durante un período de tiempo antes de volver para luchar por el derecho a ser el líder. Ellos tienen una presencia muy imponente. Se dice que pueden llamar y dar órdenes complejas a su manada con sus aullidos y ladridos.", R.mipmap.granjaggi, R.raw.granjaggi, R.raw.granjaggiintro)
        val monstruo45 = item_Monstruo("Gypceros", "Wyvern Pájaro", "Grande", "Sin elemento", 1, "Wyverns capaces de generar desconcertantes destellos de luz con sus crestas prominentes. Su piel elástica es resistente a las armas contundentes y las trampas de choque. Atención: la saliva venenosa que escupen se derrama por las pendientes.", R.mipmap.gypceros, R.raw.gylceros, R.raw.gypcerosintro)
        val monstruo46 = item_Monstruo("Gypceros Morado", "Wyvern Pájaro", "Grande", "Sin elemento", 4, "Una variante de Gypceros característica por su elástica piel morada. Muy resistentes al veneno y capaces de escupir una saliva muy tóxica.", R.mipmap.gypcerosmorado, R.raw.gylceros, R.raw.notfoundintro)
        val monstruo47 = item_Monstruo("Iodrome", "Wyvern Pájaro", "Grande", "Sin elemento", 3, "Monstruos dominantes que dirigen manadas de Ioprey. Más grandes que sus hermanos y de cresta más prominente, los Iodrome escupen un veneno que roba la vida lentamente a su presa. Se encuentran sobre todo en zonas subtropicales.", R.mipmap.lodrome, R.raw.lodrome, R.raw.lodromeintro)
        val monstruo48 = item_Monstruo("Kecha Wacha", "Bestia Colmillos", "Grande", "Agua", 1, "Bestias dentudas con garras para zarandearse entre los árboles y membranas para planear. Si se les provoca, se taparán la cara con sus orejas aislándose de cualquier sonido o luz intensa.", R.mipmap.kechawacha, R.raw.kechawacha, R.raw.kechawachaintro)
        val monstruo49 = item_Monstruo("Kecha Wacha Índigo", "Bestia Colmillos", "Grande", "Fuego", 8, "Al igual que los Kecha Wacha normales, estas bestias arbóreas se cubren la cara con sus duras orejas al ser provocadas. Sin embargo, también son capaces de escupir bolas de fuego y tienen un pelaje pálido.\n", R.mipmap.kechawachaindigo, R.raw.kechawacha, R.raw.notfoundintro)
        val monstruo50 = item_Monstruo("Khezu", "Wyvern Volador", "Grande", "Rayo", 2, "Wyverns odiosos que habitan cuevas y otros lugares oscuros. Prácticamente ciegos, los Khezu cazan guiándose por el olfato y usan descargas para paralizar a su presa antes de lanzarse desde paredes y techos elevados.\n", R.mipmap.khezu, R.raw.khezu, R.raw.khezuintro)
        val monstruo51 = item_Monstruo("Khezu Rojo", "Wyvern Volador", "Grande", "Rayo", 5, "Una aterradora variante de Khezu de tono carmesí y temperamento mucho más agresivo. Sus órganos eléctricos sobredesarrollados le dan mayor variedad de ataques con los que desarmar y atrapar a sus presas.\n", R.mipmap.khezurojo, R.raw.khezu, R.raw.notfoundintro)
        val monstruo52 = item_Monstruo("Lagombi", "Bestia Colmillos", "Grande", "Hielo", 2, "Bestias de colmillos cuya cálida piel y gruesas capas de grasa les permiten sobrevivir en climas fríos. Aunque son básicamente herbívoros, en ocasiones los Lagombi aprovechan su habilidad auditiva para cazar en sigilo.\n", R.mipmap.lagombi, R.raw.lagombi, R.raw.notfoundintro)
        val monstruo53 = item_Monstruo("Monoblos", "Wyvern Volador", "Grande", "Sin elemento", 5, "Un wyvern con un solo cuerno que habita en los desiertos y puede enterrarse en la arena. El cuerno hace sus cargas letales, y aunque carece de ataques de aliento, su rugido es capaz de destrozar el tímpano humano.\n", R.mipmap.monoblos, R.raw.monoblos, R.raw.monoblosintro)
        val monstruo54 = item_Monstruo("Monoblos Blanco", "Wyvern Volador", "Grande", "Sin elemento", 6, "Una variedad de Monoblos con una cobertura parecida al yeso. Más agresivo que sus parientes comunes, el Monoblos Blanco nunca deja de perseguir a una presa cuando se ha fijado en ella.", R.mipmap.monoblosblanco, R.raw.monoblos, R.raw.notfoundintro)
        val monstruo55 = item_Monstruo("Najarala", "Wyvern Serpiente", "Grande", "Sin elemento", 2, "Monstruo que aturde a su presa con la vibración de sus escamas para luego enroscarse sobre ella y estrangularla. Si un Najarala se enrosca sobre ti, una huida rápida o matarlo rápidamente son tus únicas posibilidades.\n", R.mipmap.najarala, R.raw.najarala, R.raw.najaralaintro)
        val monstruo56 = item_Monstruo("Najarala Abisal", "Wyvern Serpiente", "Grande", "Agua", 8, "Un tipo de Najarala que utiliza su largo cuerpo de forma letal. El Najarala abisal escupe una sustancia acuosa a sus presas, y puede usar sus escamas para guiar el líquido a los objetivos más esquivos.\n", R.mipmap.najaralaabisal, R.raw.najarala, R.raw.notfoundintro)
        val monstruo57 = item_Monstruo("Nerscylla", "Temnoceran", "Grande", "Sin elemento", 2, "Un Temnoceran que teje redes para defender su territorio y cazar. Debilitan a sus presas, las inmovilizan y devoran con sus grandes mandíbulas. También les gusta cubrirse con pieles de los Gypceros que consumen.\n", R.mipmap.nerscylla, R.raw.nerscylla, R.raw.nerscyllaintro)
        val monstruo58 = item_Monstruo("Nerscylla Sombrío", "Temnoceran", "Grande", "Sin elemento", 9, "Temnoceran del desierto que atrae a las presas a trampas de arena y las desgarra con sus mandíbulas en forma de tijera. Al igual que otras variedades, llevan las pieles de sus víctimas, que a menudo son Khezu.\n", R.mipmap.nerscyllasombrio, R.raw.nerscylla, R.raw.notfoundintro)
        val monstruo59 = item_Monstruo("Rajang", "Bestia Colmillos", "Grande", "Rayo", 7, "Ultraagresiva criatura a la que muy pocos han sobrevivido. Los que lo han logrado dicen que ataca de forma extraña. El aislamiento y la forma de vida solitaria del Rajang dificultan el estudio de sus hábitos territoriales\n", R.mipmap.rajang, R.raw.rajang, R.raw.rajangintro)
        val monstruo60 = item_Monstruo("Rajang Furioso", "Bestia Colmillos", "Grande", "Rayo", 10, "Variedad de Rajang con una melena dorada. Lanza ataques a distancia y usando muros. Al enfurecerse, brilla con un fulgor dorado.", R.mipmap.rajangfurioso, R.raw.rajang, R.raw.notfoundintro)
        val monstruo61 = item_Monstruo("Rathalos", "Wyvern Volador", "Grande", "Fuego", 3, "Terribles wyverns llamados \"Reyes de los cielos\". Junto con las Rathian, acechan amplios territorios cerca de sus nidos. Los Rathalos descienden sobre los invasores desde el cielo, atacando con veneno, garras y fuego.\n", R.mipmap.rathalos, R.raw.rathalos, R.raw.rathalosintro)
        val monstruo62 = item_Monstruo("Rathalos Celeste", "Wyvern Volador", "Grande", "Fuego", 6, "Una subespecie de tono azulado de Rathalos. Con mejor movilidad que sus parientes normales, son capaces de localizar a su presa desde el aire y lanzarse prestos a matar. Cuando estos maestros de la caza eligen un objetivo, no hay mucha esperanza de huir.\n", R.mipmap.rathalosceleste, R.raw.rathalos, R.raw.notfoundintro)
        val monstruo63 = item_Monstruo("Rathalos Plateado", "Wyvern Volador", "Grande", "Fuego", 7, "Rara variante de Rathalos de bello cuerpo plateado como el sol. Muchos son los misterios que rodean a su comportamiento y fisionomía, incluido el origen de su capa plateada.\n", R.mipmap.rathalosplateado, R.raw.rathalos, R.raw.notfoundintro)
        val monstruo64 = item_Monstruo("Rathian", "Wyvern Volador", "Grande", "Fuego", 2, "Wyverns hembras que lanzan fuego también denominadas \"Reinas de la tierra\". De patas poderosas y cola venenosa, suelen cazar en tierra. Las Rathian a veces cazan en pareja con un Rathalos, con los que parecen coordinar sus ataques.\n", R.mipmap.rathian, R.raw.rathian, R.raw.rathianintro)
        val monstruo65 = item_Monstruo("Rathian Rosa", "Wyvern Volador", "Grande", "Fuego", 5, "Una subespecie de Rathian de escamas color rosa vivo. Las Rathian rosas blanden su cola tóxica con más destreza que una Rathian normal, y usan una amplia gama de ataques para debilitar a la presa antes de matarla.\n", R.mipmap.rathianrosa, R.raw.rathian, R.raw.notfoundintro)
        val monstruo66 = item_Monstruo("Rathian Dorada", "Wyvern Volador", "Grande", "Fuego", 7, "Escasa variante de Rathian de cuerpo dorado como la luna. Muchos son los misterios que rodean a su comportamiento y fisionomía, incluido el origen de su capa dorada.\n", R.mipmap.rathiandorada, R.raw.rathian, R.raw.notfoundintro)
        val monstruo67 = item_Monstruo("Seltas", "Neopteron", "Grande", "Sin elemento", 1, "Un neopteron de medio tamaño que ataca velozmente a todo intruso desde las alturas. Se caracteriza por almacenar un líquido corrosivo en su cuerpo para dispararlo desde su abdomen en forma de aguijón.", R.mipmap.seltas, R.raw.seltas, R.raw.seltasintro)
        val monstruo68 = item_Monstruo("Seltas Sílice", "Neopteron", "Grande", "Sin elemento", 8, "Un neopteron de tamaño medio cuyos cuernos y el alcance de sus patas delanteras lo distinguen de sus parientes cercanos. Los Seltas Sílice son notables por su capacidad para excavar vastas madrigueras en el suelo.\n", R.mipmap.seltassilice, R.raw.seltas, R.raw.notfoundintro)
        val monstruo69 = item_Monstruo("Seltas Reina", "Neopteron", "Grande", "Agua", 3, "Neopterones hembra que son incapaces de volar por sí solas, y que liberan feromonas para atraer a Seltas macho, a los que someten. Aunque de caparazón duro, las mucosas de las fauces de una Seltas reina son débiles cuando están expuestas.\n", R.mipmap.seltasreina, R.raw.seltasreina, R.raw.seltasreinaintro)
        val monstruo70 = item_Monstruo("Seltas Sílice Reina", "Neopteron", "Grande", "Agua", 9, "Un neopteron grande que utiliza las pinzas de su cola para atrapar Seltas macho... o cualquier cosa que pueda suponer una amenaza. Cuando captura a un macho, la variedad silícea puede llegar a arrojarlo contra sus enemigos.\n", R.mipmap.seltassilicereina, R.raw.seltasreina, R.raw.notfoundintro)
        val monstruo71 = item_Monstruo("Seregios", "Wyvern Volador", "Grande", "Sin elemento", 9, "Una raza de wyvern que apenas se ha dejado ver estos últimos años por estas tierras. Famosos por poder lanzar escamas afiladas a sus presas y por utilizarlas para blandirlas contra todos aquellos que los amenacen.\n", R.mipmap.seregios, R.raw.seregios, R.raw.seregiosintro)
        val monstruo72 = item_Monstruo("Tetsucabra", "Anfibio", "Grande", "Sin elemento", 1, "Anfibios de grandes mandíbulas y colmillos singulares que usan para moverse entre las rocas para cazar. Usan sus poderosas patas traseras para atravesar terrenos escarpados. La cola les ayuda a moverse, pero si se agotan pueden ser vulnerables.\n", R.mipmap.tetsucabra, R.raw.tetsucabra, R.raw.tetsucabraintro)
        val monstruo73 = item_Monstruo("Tetsucabra Berserker", "Anfibio", "Grande", "Sin elemento", 8, "Un monstruo anfibio conocido por sus peculiares marcas, que se asemejan a una cara pintada. Estas bestias utilizan rocas igual que los Tetsucabra normales, pero las de esta variedad estallan al impactar.\n", R.mipmap.tetsucabraberserker, R.raw.tetsucabra, R.raw.notfoundintro)
        val monstruo74 = item_Monstruo("Tigrex", "Wyvern Volador", "Grande", "Sin elemento", 3, "Wyverns voladores cuyo primitivo origen parece obvio. De instinto agresivo, usan sus garras, mandíbulas y musculosas patas con gran ferocidad. Habitan una zona amplia y se han avistado incluso en Canal Helado.\n", R.mipmap.tigrex, R.raw.tigrex, R.raw.tigrexintro)
        val monstruo75 = item_Monstruo("Tigrex Pardo", "Wyvern Volador", "Grande", "Sin elemento", 6, "Una subespecie de Tigrex de individuos tan brutales como famélicos. Predominan en zonas volcánicas, pero pueden habitar en muchos climas. Sus aullidos son aún más desgarradores que los del Tigrex normal, y se oyen a grandísimas distancias.\n", R.mipmap.tigrexpardo, R.raw.tigrex, R.raw.notfoundintro)
        val monstruo76 = item_Monstruo("Tigrex Ígneo", "Wyvern Volador", "Grande", "Sin elemento", 7, "Variante de Tigrex poco común de cuya existencia se especula tras el descubrimiento de marcas de garras mucho más grandes que las de un Tigrex normal. No se han dado avistamientos, por lo que su existencia sigue siendo puramente hipotética.\n", R.mipmap.tigrexigneo, R.raw.tigrex, R.raw.notfoundintro)
        val monstruo77 = item_Monstruo("Ukanlos", "Wyvern Volador", "Grande", "Hielo", 7, "Un enigmático dragón encontrado en las profundidades de las simas más remotas. Sus mandíbulas son capaces de destrozar hielo y rocas por igual. En cierta región se afirma que su aspecto es idéntico al del dios que veneran sus leyendas.\n", R.mipmap.ukanlos, R.raw.ukanlos, R.raw.ukanlosintro)
        val monstruo78 = item_Monstruo("Velocidrome", "Wyvern Pájaro", "Grande", "Sin elemento", 3, "Monstruos dominantes que dirigen las manadas de Velociprey. Más grandes que sus primos y de cresta más prominente, los Velocidrome usan sus fuertes patas traseras para saltar sobre su presa, inmovilizándola antes de llamar a sus compañeros.\n", R.mipmap.velocidrome, R.raw.velocidromeygendrome, R.raw.velocidromeintro)
        val monstruo79 = item_Monstruo("Yian Garuga", "Wyvern Pájaro", "Grande", "Fuego", 5, "Un pariente cercano del Yian Kut-Ku, famoso por sus escamas duras y negras, y sus mechones de melena blanca. Estos listos monstruos son famosos por evitar trampas y usar sus colas venenosas con efectos letales; son muy peligrosos.\n", R.mipmap.yiangaruga, R.raw.yiangaruga, R.raw.yiangarugaintro)
        val monstruo80 = item_Monstruo("Yian Kut-Ku", "Wyvern Pájaro", "Grande", "Fuego", 3, "Wyvern pájaro de enorme pico y grandes orejas, que expande al enfadarse. De agudo oído, le molestan los ruidos fuertes. Más pequeño y rápido que otros wyverns.\n", R.mipmap.yiankutku, R.raw.yiankutku, R.raw.yiankutkuintro)
        val monstruo81 = item_Monstruo("Yian Kut-Ku Azul", "Wyvern Pájaro", "Grande", "Fuego", 4, "Una variante de Yian Kut-Ku protegida por un caparazón azul. Comparte la debilidad frente a ruidos fuertes del Yian Kut-Ku normal, pero cuando se enfada demuestra mucha más fuerza.\n", R.mipmap.yiankutkuazul, R.raw.yiankutku, R.raw.notfoundintro)
        val monstruo82 = item_Monstruo("Zamtrios", "Anfibio", "Grande", "Hielo", 2, "Anfibios que atacan desde zonas heladas, aprovechando el frío para aturdir a sus presas. Segregan un liquido especial que cubre su cuerpo de una armadura de hielo y congela cualquier enemigo cercano. Su comida favorita son las ranas.\n", R.mipmap.zamtrios, R.raw.zamtrios, R.raw.zamtriosintro)
        val monstruo83 = item_Monstruo("Zamtrios Tigre", "Anfibio", "Grande", "Agua", 8, "Al contrario que su contrapartida estándar, esta variedad rayada de Zamtrios habita por lo común en climas desérticos y es capaz de aprovechar su habilidad para modificar su cuerpo incluso en movimiento, lo que lo hace aún más peligroso.\n", R.mipmap.zamtriostigre, R.raw.zamtrios, R.raw.notfoundintro)
        val monstruo84 = item_Monstruo("Zinogre", "Wyvern Colmillos", "Grande", "Rayo", 3, "Wyverns de colmillos con el cuerpo cargado de electricidad. Sus extremidades y sus fuertes garras les permiten prosperar en zonas montañosas. En las cacerías, a menudo reúnen muchos bichos eléctricos, lo que les da un estado de sobrecarga.\n", R.mipmap.zinogre, R.raw.zinogre, R.raw.zinogreintro)
        val monstruo85 = item_Monstruo("Zinogre Estigio", "Wyvern Colmillos", "Grande", "Draco", 6, "Una subespecie de Zinogre de cuerpo negro. Reúne bichos que comen semillas dragón, y canaliza su energía de dragón para aumentar su propio poder.\n", R.mipmap.zinogreestigio, R.raw.zinogre, R.raw.notfoundintro)
        val monstruo86 = item_Monstruo("Kirin", "Dragón Anciano", "Grande", "Rayo", 5, "Dragón anciano tan escaso que apenas se sabe de su ecología, aunque todos conocen el gran valor de las partes de Kirin. Se ha dicho que son el mismo rayo, y que su cuerpo se cubre de electricidad al provocarlos.\n", R.mipmap.kirin, R.raw.kirin, R.raw.kirinintro)
        val monstruo87 = item_Monstruo("Kirin Boreal", "Dragón Anciano", "Grande", "Hielo", 5, "No existen avistamientos fiables de estas huidizas criaturas. Los pocos informes que hay dicen que la temperatura cae cada vez que aparecen, y que toda humedad del aire se congela de forma espontánea.\n", R.mipmap.kirinboreal, R.raw.kirin, R.raw.notfoundintro)
        val monstruo88 = item_Monstruo("Dah'ren Mohran", "Dragón Anciano", "Grande", "Sin elemento", 3, "Dragones ancianos colosales que nadan en el Gran desierto, rompiendo obstáculos con sus cuernos en espiral. Su peculiar color proviene de una capa de metales oxidados y otros metales que se acumulan en su piel a lo largo de sus longevas vidas.\n", R.mipmap.dahrenmohran, R.raw.dahrenmohran, R.raw.dahrenmohranintro)
        val monstruo89 = item_Monstruo("Chameleos", "Dragón Anciano", "Grande", "Agua", 10, "Pocos han conseguido ver a este dragón anciano, por lo que se cree que puede confundirse con el entorno como un camaleón... de ahí su nombre. Dicen que los ataques parecen surgir de la nada, pero se puede ver a la bestia con bombas de humo.\n", R.mipmap.chameleos, R.raw.chameleos, R.raw.chameleosintro)
        val monstruo90 = item_Monstruo("Kushala Daora", "Dragón Anciano", "Grande", "Hielo", 7, "Hasta acercarse a uno de estos dragones metálicos es difícil, pero dicen que es más fácil si has debilitado a la criatura con veneno, o si tiene a otro cazador subido a su espalda, limitando la presión del aire que puede generar.\n", R.mipmap.kushaladaora, R.raw.kushaladaora, R.raw.kushaladaoraintro)
        val monstruo91 = item_Monstruo("Kushala Daora Oxidado", "Dragón Anciano", "Grande", "Hielo", 10, "El Kushala Daora Oxidado suele encontrarse en la Ciudad o en la Caserna, pero también ha habido avistamientos de él en la Zona Polar, quizá debido a que esa zona tan inhóspita es ideal para mudar de piel sin ninguna molestia.\n", R.mipmap.kushaladaoraoxidado, R.raw.kushaladaora, R.raw.kushaladaoraoxidadointro)
        val monstruo92 = item_Monstruo("Teostra", "Dragón Anciano", "Grande", "Fuego", 7, "Dragones ancianos brutales cubiertos de llamas que expelen fuego ardiente. Los Teostra son de una naturaleza tan fiera y letal que el Gremio los tiene controlados siempre que puede.\n", R.mipmap.teostra, R.raw.teostra, R.raw.teostraintro)
        val monstruo93 = item_Monstruo("Dalamadur", "Dragón Anciano", "Grande", "Sin elemento", 7, "Un Dragón Anciano enorme, de un tamaño descomunal. La única mención de su existencia está solo en los cuentos, que dicen que puede doblegar la faz del mundo y aplastar montañas con un solo movimiento.\n", R.mipmap.dalamadur, R.raw.dalamadur, R.raw.dalamadurintro)
        val monstruo94 = item_Monstruo("Zar Dalamadur", "Dragón Anciano", "Grande", "Sin elemento", 10, "Una subespecie de Dalamadur con espinas rojas en la espalda. Aunque su existencia estaba en duda, los últimos años han sido testigos de muchos avistamientos. Se teme que la aparición de Zar Dalamadur sea presagio de un futuro terrible.\n", R.mipmap.zardalamadur, R.raw.dalamadur, R.raw.zardalamadurintro)
        val monstruo95 = item_Monstruo("Gogmazios", "Dragón Anciano", "Grande", "Fuego", 10, "Impregnado de un fluido pegajoso, a este gigantesco dragón anciano no parece pesarle el Matadragones de su lomo. Los testigos afirman que, a pesar de su gran tamaño, esta misteriosa bestia es capaz de alzar el vuelo.\n", R.mipmap.gogmazios, R.raw.gogmazios, R.raw.gogmaziosintro)
        val monstruo96 = item_Monstruo("Fatalis", "Dragón negro", "Grande", "Fuego", 10, "Las leyendas sobre este dragón se remontan a la antiguedad. Mucho son los cazadores que han intentado desafiarlo, pero ninguno de ellos ha sobrevivido. Un monstruo rodeado de misterio.", R.mipmap.interrogante, R.raw.fatalis, R.raw.fatalisintro)
        val monstruo97 = item_Monstruo("Fatalis Carmesí", "Dragón negro", "Grande", "Fuego", 10, "Las leyendas sobre este dragón se remontan a la antigüedad. Muchos son los cazadores que han intentado desafiarlo, pero ninguno de ellos ha sobrevivido. Un monstruo rodeado de misterio.\n", R.mipmap.interrogante, R.raw.fatalis, R.raw.fataliscarmesiintro)
        val monstruo98 = item_Monstruo("Fatalis Blanco", "Dragón negro", "Grande", "Rayo", 10, "Las leyendas sobre este dragón se remontan a la antiguedad. Mucho son los cazadores que han intentado desafiarlo, pero ninguno de ellos ha sobrevivido. Un monstruo rodeado de misterio.\n", R.mipmap.interrogante, R.raw.fatalis, R.raw.fatalisblancointro)
        val nombre = intent.getStringExtra("Nombre")
        val especie = intent.getStringExtra("Especie")
        val tamano = intent.getStringExtra("Tamaño")
        val elemento = intent.getStringExtra("Elemento")
        val hostilidad = intent.getIntExtra("Hostilidad", 0)
        val tvNoFound = findViewById<TextView>(R.id.tvNoFound)
        val lista = findViewById<GridView>(R.id.gvLista)
        var listaMonstruos = listOf(monstruo, monstruo2, monstruo3, monstruo4, monstruo5, monstruo6, monstruo7, monstruo8, monstruo9, monstruo10, monstruo11, monstruo12, monstruo13, monstruo14, monstruo15, monstruo16, monstruo17, monstruo18, monstruo19, monstruo20, monstruo21, monstruo22, monstruo23, monstruo24, monstruo25, monstruo26, monstruo27, monstruo28, monstruo29, monstruo30, monstruo31, monstruo32, monstruo33, monstruo34, monstruo35, monstruo36, monstruo37, monstruo38, monstruo39, monstruo40, monstruo41, monstruo42, monstruo43, monstruo44, monstruo45, monstruo46, monstruo47, monstruo48, monstruo49, monstruo50, monstruo51, monstruo52, monstruo53, monstruo54, monstruo55, monstruo56, monstruo57, monstruo58, monstruo59, monstruo60, monstruo61, monstruo62, monstruo63, monstruo64, monstruo65, monstruo66, monstruo67, monstruo68, monstruo69, monstruo70, monstruo71, monstruo72, monstruo73, monstruo74, monstruo75, monstruo76, monstruo77, monstruo78, monstruo79, monstruo80, monstruo81, monstruo82, monstruo83, monstruo84, monstruo85, monstruo86, monstruo87, monstruo88, monstruo89, monstruo90, monstruo91, monstruo92, monstruo93, monstruo94, monstruo95, monstruo96, monstruo97, monstruo98)
        listar(listaMonstruos, nombre!!, especie!!, tamano!!, elemento!!, hostilidad)

        if (listaMonstruosFiltrada.isEmpty()) {
            tvNoFound.visibility = View.VISIBLE
            lista.visibility = View.GONE
        } else {
            tvNoFound.visibility = View.GONE
            lista.visibility = View.VISIBLE
            val adapter = MonsterAdapter(this, listaMonstruosFiltrada)
            lista.adapter = adapter
        }



        lista.setOnItemClickListener { parent, view, position, id ->
            val monstruoSelecionado = listaMonstruosFiltrada[position]

            var grito = MediaPlayer.create(this, monstruoSelecionado.grito!!)

            grito?.start()

            val intent = Intent(this,DetallesActivity::class.java)
            intent.putExtra("monstruo", listaMonstruosFiltrada[position])
            startActivity(intent)
        }
    }
    private lateinit var listaMonstruosFiltrada: List<item_Monstruo>

    private fun listar(listaMonstruos: List<item_Monstruo>, nombre:String, espe:String, tama:String, ele:String, hos:Int) {
        if (!nombre.isEmpty()) {
            listaMonstruosFiltrada = listaMonstruos.filter { it.nombre.uppercase().contains(nombre!!.uppercase()) }
        } else {
            if (hos == 0) {
                listaMonstruosFiltrada = listaMonstruos.filter { it.nombre.uppercase().contains(nombre!!.uppercase()) && espe.contains(it.especies) && ele.contains(it.elemento) && tama.contains(it.tamano)}
            } else {
                listaMonstruosFiltrada = listaMonstruos.filter { it.nombre.uppercase().contains(nombre!!.uppercase()) && espe.contains(it.especies) && it.elemento.contains(ele!!) && tama.contains(it.tamano) && it.hostil == hos}
            }
        }
    }
}